homeassistant:
  customize: !include customize.yaml

alexa: !include alexa.yaml
alexa_media: !include alexa_media.yaml
analytics:
automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensor.yaml
cloud:
counter:
compensation: !include compensation.yaml
config:
conversation:
cover: !include cover.yaml
discovery:
energy:
frontend:
  themes: !include_dir_merge_named themes/
group: !include group.yaml
harmony_helper: !include harmony_helper.yaml
history: !include history.yaml
http: !include http.yaml
input_boolean:
input_select:
input_text:
input_datetime:
input_number:
intent_script: !include intent_script.yaml
ios:
light: !include light.yaml
logbook:
logger: !include logger.yaml
lovelace: !include lovelace.yaml
lovelace_gen:
media_player: !include media_player.yaml
media_source:
mobile_app:
my:
notify: !include notify.yaml
person: 
plant: !include plants.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/
sensor: !include sensor.yaml
sun:
switch: !include switch.yaml
system_health:
template: !include_dir_merge_list template
timer:
weather: !include weather.yaml