homeassistant:
  customize: !include customize.yaml

alexa: !include alexa.yaml
analytics:
automation: !include automations.yaml
automation directory: !include_dir_merge_list automation
command_line: !include_dir_merge_list command_line
compensation: !include compensation.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes/
group:
hardware:
harmony_helper: !include harmony_helper.yaml
homekit: !include homekit.yaml
http: !include http.yaml
intent_script: !include intent_script.yaml
light: !include_dir_merge_list light
logger: !include logger.yaml
lovelace: !include lovelace.yaml
lovelace_gen:
media_player: !include media_player.yaml
mqtt: !include_dir_merge_named mqtt/
notify: !include notify.yaml
plant: !include plants.yaml
python_script:
recorder: !include recorder.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/
sensor: !include sensor.yaml
switch: !include switch.yaml
system_health:
template: !include_dir_merge_list template
