homeassistant:
  customize: !include customize.yaml

alexa: !include alexa.yaml
alexa_media: !include alexa_media.yaml
apcupsd:
  host: a722577e-apcupsd
automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensor.yaml
camera: !include cameras.yaml
cloud:
config:
conversation:
cover: !include cover.yaml
discovery: !include discovery.yaml
frontend: !include frontend.yaml
group: !include group.yaml
history: !include history.yaml
http:
  base_url: !secret http_base_url
image_processing: !include image_processing.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
intent_script: !include intent_script.yaml
ios:
light: !include light.yaml
logbook:
logger: !include logger.yaml
lovelace:
  mode: yaml
map:
media_player: !include media_player.yaml
mobile_app:
notify: !include notify.yaml
panel_custom: !include panel_custom.yaml
person: 
recorder: !include recorder.yaml
remote: !include remote.yaml
roku: !include roku.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
speedtestdotnet: !include speedtestdotnet.yaml
sun:
switch: !include switch.yaml
system_health:
weather: !include weather.yaml
updater:
  include_used_components: true
zwave: !include zwave.yaml