# SNMP

- platform: snmp
  host: !secret synology_host
  unique_id: 93aeca84-06d8-498e-9f72-ced1045b4451
  name: Synology Uptime
  baseoid: 1.3.6.1.2.1.25.1.1.0
  <<: &uptime
    value_template: >
      {{ (now() - timedelta(seconds=value | int(0) / 100)).isoformat() }}

# MULTIZONE CONTROLLER

- platform: multizone_controller
  unique_id: active_media_player
  zones:
    - source: media_player.yamaha_rx_v6a
    - source: media_player.yamaha_rx_v6a_zone2
  snap_volume: true
  volume_increment: 0.05
  volume_max: 1.0
  volume_min: 0.0

- platform: multizone_controller
  unique_id: active_media_player_basement
  zones:
    - source: media_player.yamaha_receiver
    - source: media_player.yamaha_receiver_zone_2
  snap_volume: true
  volume_increment: 0.05
  volume_max: 1.0
  volume_min: 0.2

# FILTERS

- platform: filter
  name: Master Bathroom Filtered Humidity
  unique_id: e3ad361d-a3f7-4edd-a236-6b0ff839baa0
  entity_id: sensor.master_bathroom_humidity
  filters:
    - filter: lowpass
      time_constant: 10
      precision: 2

# STATISTICS

- platform: statistics
  name: Master Bathroom Filtered Humidity Statistics
  unique_id: 48f6ebd3-6181-4d9a-be8a-83d101de394d
  entity_id: sensor.master_bathroom_filtered_humidity
  sampling_size: 172800
  state_characteristic: mean
  max_age:
    days: 1

# HISTORY STATS

- platform: history_stats
  name: Petro at Work
  unique_id: 532ca91c-17ed-4ea9-b95b-f14bc1673110
  entity_id: person.petro
  state: !secret petro_work
  type: time
  <<: &timeframe
    start: >
      {% set sensor = 'sensor.monday_this_week' %}
      {% if sensor | has_value %}
        {{ states(sensor) | as_datetime | as_local }}
      {% else %}
        {% set n = today_at() %}
        {{ n - timedelta(days=n.weekday()) }}
      {% endif %}
    end: "{{ now() }}"

- platform: history_stats
  name: Lambo at Work
  unique_id: 57a1843e-8aeb-43da-8d5b-4d06031140e4
  entity_id: person.lambo
  state: !secret lambo_work
  type: time
  <<: *timeframe
