# MULTIZONE CONTROLLER

- platform: multizone_controller
  unique_id: active_media_player
  zones:
    - source: media_player.yamaha_rx_v6a
    - source: media_player.yamaha_rx_v6a_zone2
  snap_volume: true
  volume_increment: 0.05
  volume_max: 1.0
  volume_min: 0.0

- platform: multizone_controller
  unique_id: active_media_player_basement
  zones:
    - source: media_player.yamaha_receiver
    - source: media_player.yamaha_receiver_zone_2
  snap_volume: true
  volume_increment: 0.05
  volume_max: 1.0
  volume_min: 0.2

# HISTORY STATS

- platform: history_stats
  name: Petro at Work
  unique_id: 532ca91c-17ed-4ea9-b95b-f14bc1673110
  entity_id: person.petro
  state: !secret petro_work
  type: time
  <<: &timeframe
    start: >
      {% set sensor = 'sensor.monday_this_week' %}
      {% if sensor | has_value %}
        {{ states(sensor) | as_datetime | as_local }}
      {% else %}
        {% set n = today_at() %}
        {{ n - timedelta(days=n.weekday()) }}
      {% endif %}
    end: "{{ now() }}"

- platform: history_stats
  name: Lambo at Work
  unique_id: 57a1843e-8aeb-43da-8d5b-4d06031140e4
  entity_id: person.lambo
  state: !secret lambo_work
  type: time
  <<: *timeframe
