  # Time and Date / Unused
      
  - platform: time_date
    display_options:
      - time
      - date_time
      - date
  
  # SNMP
  
  - platform: snmp
    host: !secret unifi_bonus_switch
    name: Bonus Room Switch Temperature
    unit_of_measurement: "°C"
    baseoid: 1.3.6.1.4.1.4413.1.1.43.1.8.1.5.1.0

  - platform: snmp
    host: !secret unifi_bonus_switch
    name: Bonus Room Switch Uptime
    baseoid: 1.3.6.1.2.1.1.3.0
    value_template: >
      {{ (now().timestamp() - (value | int(default=0) / 100)) | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False, now().isoformat()) }}
      
  - platform: snmp
    host: !secret unifi_server_switch
    name: Server Room Switch Temperature
    unit_of_measurement: "°C"
    baseoid: 1.3.6.1.4.1.4413.1.1.43.1.8.1.5.1.0
      
  - platform: snmp
    host: !secret unifi_server_switch
    name: Server Room Switch Uptime
    baseoid: 1.3.6.1.2.1.1.3.0
    value_template: >
      {{ (now().timestamp() - (value | int(default=0) / 100)) | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False, now().isoformat()) }}
      
  - platform: snmp
    host: !secret unifi_server_gateway
    name: Server Room Gateway Uptime
    baseoid: 1.3.6.1.2.1.1.3.0
    value_template: >
      {{ (now().timestamp() - (value | int(default=0) / 100)) | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False, now().isoformat()) }}
      
  - platform: snmp
    host: !secret unifi_garage_ac_lite
    name: Garage AC Lite Uptime
    baseoid: 1.3.6.1.2.1.1.3.0
    value_template: >
      {{ (now().timestamp() - (value | int(default=0) / 100)) | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False, now().isoformat()) }}
     
  - platform: snmp
    host: !secret unifi_closet_ac_lite
    name: Hall Closet AC Lite Uptime
    baseoid: 1.3.6.1.2.1.1.3.0
    value_template: >
      {{ (now().timestamp() - (value | int(default=0) / 100)) | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False, now().isoformat()) }}
     
  - platform: snmp
    host: !secret unifi_server_ac_lite
    name: Server Room AC Lite Uptime
    baseoid: 1.3.6.1.2.1.1.3.0
    value_template: >
      {{ (now().timestamp() - (value | int(default=0) / 100)) | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False, now().isoformat()) }}
     

  - platform: snmp
    host: !secret synology_host
    name: Synology Uptime
    baseoid: 1.3.6.1.2.1.25.1.1.0
    value_template: >
      {{ (now().timestamp() - (value | int(default=0) / 100)) | timestamp_custom('%Y-%m-%dT%H:%M:%S.%f+00:00', False, now().isoformat()) }}

  - platform: multizone_controller
    unique_id: active_media_player
    zones:
      - source: media_player.yamaha_rx_v6a
      - source: media_player.yamaha_rx_v6a_zone2
    snap_volume: true
    volume_increment: 0.05
    volume_max: 1.0
    volume_min: 0.0

  - platform: multizone_controller
    unique_id: active_media_player_basement
    zones:
      - source: media_player.yamaha_receiver
      - source: media_player.yamaha_receiver_zone_2
    snap_volume: true
    volume_increment: 0.05
    volume_max: 1.0
    volume_min: 0.2

  - platform: filter
    name: Master Bathroom Filtered Humidity
    entity_id: sensor.master_bathroom_humidity
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 2

  - platform: statistics
    name: Master Bathroom Filtered Humidity Statistics
    entity_id: sensor.master_bathroom_filtered_humidity
    sampling_size: 172800
    state_characteristic: mean
    max_age:
      days: 1

- platform: derivative
  name: Master Bathroom Humidity Change
  source: sensor.master_bathroom_filtered_humidity
  unit: "%"

- platform: history_stats
  name: Petro at Work
  unique_id: 532ca91c-17ed-4ea9-b95b-f14bc1673110
  entity_id: person.petro
  state: !secret petro_work
  type: time
  <<: &timeframe
    start: >
      {% set sensor = 'sensor.monday_this_week' %}
      {% if sensor | has_value %}
        {{ states(sensor) | as_datetime | as_local }}
      {% else %}
        {% set n = today_at() %}
        {{ n - timedelta(days=n.weekday()) }}
      {% endif %}
    end: "{{ now() }}"

- platform: history_stats
  name: Lambo at Work
  unique_id: 57a1843e-8aeb-43da-8d5b-4d06031140e4
  entity_id: person.lambo
  state: !secret lambo_work
  type: time
  <<: *timeframe
