# Test Switches

- platform: demo

# Template Switches

- platform: template
  switches:
            
      # INSIDE LIGHTS SWITCH
      inside:
        value_template: "{{ is_state('group.inside','on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.inside
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.inside
      
      # OUTSIDE LIGHTS SWITCH
      outside:
        value_template: "{{ is_state('group.outside','on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.outside
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.outside
      
      # UPSTAIRS LIGHTS SWITCH
      upstairs:
        value_template: "{{ is_state('group.upstairs','on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.upstairs
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.upstairs
      
      # DOWNSTAIRS LIGHTS SWITCH
      downstairs:
        value_template: "{{ is_state('group.downstairs','on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.downstairs
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.downstairs
            
      # ZONE 1 MEDIA SWITCH
      zone_1:
        value_template: "{{ is_state('media_player.yamaha_receiver', 'on') }}"
        turn_on:
          service: media_player.turn_on
          entity_id: media_player.yamaha_receiver
        turn_off:
          service: media_player.turn_off
          entity_id: media_player.yamaha_receiver
            
      # ZONE 2 MEDIA SWITCH
      zone_2:
        value_template: "{{ is_state('media_player.yamaha_receiver_zone_2', 'on') }}"
        turn_on:
          service: media_player.turn_on
          entity_id: media_player.yamaha_receiver_zone_2
        turn_off:
          service: media_player.turn_off
          entity_id: media_player.yamaha_receiver_zone_2
      
      # XBOX HARMONY ACTIVITY
      xbox_one:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Xbox One') }}"
        turn_on:
          - service: remote.turn_on
            data:
              entity_id: remote.living_room
              activity: 'Xbox One'
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Xbox One') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      
      # PLAYSTATION HARMONY ACTIVITY
      ps4:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'PS4') }}"
        turn_on:
          - service: remote.turn_on
            data:
              entity_id: remote.living_room
              activity: 'PS4'
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'PS4') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      
      # SWITCH HARMONY ACTIVITY
      switch:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Switch') }}"
        turn_on:
          - service: remote.turn_on
            data:
              entity_id: remote.living_room
              activity: 'Switch'
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Switch') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      
      # TV HARMONY ACTIVITY
      tv:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'TV') }}"
        turn_on:
          - service: remote.turn_on
            data:
              entity_id: remote.living_room
              activity: 'TV'
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'TV') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
      
      # OFF ACTIVITY
      poweroff:
        value_template: "{{ not is_state_attr('remote.living_room', 'current_activity', 'PowerOff') }}"
        turn_on:
          - service: remote.turn_on
            data:
              entity_id: remote.living_room
              activity: 'PowerOff'
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'PowerOff') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          - service: remote.turn_on
            data:
              entity_id: remote.living_room
              activity: 'PowerOff'
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'PowerOff') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        
      # ROKU HARMONY ACTIVITY
      roku:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Roku') }}"
        turn_on:
          - service: remote.turn_on
            data:
              entity_id: remote.living_room
              activity: 'Roku'
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Roku') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: 'PowerOff'
            
      # NETFLIX
      netflix:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Netflix') }}
        turn_on:
          - service: script.roku
          - wait_template: "{{ is_state('switch.roku', 'on') }}"
          - service: media_player.select_source
            data:
              entity_id: media_player.roku_living_room
              source: Netflix
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Roku') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          - service: switch.turn_off
            entity_id: switch.roku
            
      # HBO NOW
      hbo_now:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'HBO NOW') }}
        turn_on:
          - service: script.roku
          - wait_template: "{{ is_state('switch.roku', 'on') }}"
          - service: media_player.select_source
            data:
              entity_id: media_player.roku_living_room
              source: HBO NOW
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Roku') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          - service: switch.turn_off
            entity_id: switch.roku
            
      # Hulu
      hulu:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Hulu') }}
        turn_on:
          - service: script.roku
          - wait_template: "{{ is_state('switch.roku', 'on') }}"
          - service: media_player.select_source
            data:
              entity_id: media_player.roku_living_room
              source: Hulu
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Roku') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          - service: switch.turn_off
            entity_id: switch.roku
            
      # Prime Video
      prime_video:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Prime Video') }}
        turn_on:
          - service: script.roku
          - wait_template: "{{ is_state('switch.roku', 'on') }}"
          - service: media_player.select_source
            data:
              entity_id: media_player.roku_living_room
              source: Prime Video
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Roku') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          - service: switch.turn_off
            entity_id: switch.roku
            
      # Disney Plus
      disney_plus:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Disney Plus') }}
        turn_on:
          - service: script.roku
          - wait_template: "{{ is_state('switch.roku', 'on') }}"
          - service: media_player.select_source
            data:
              entity_id: media_player.roku_living_room
              source: Disney Plus
          - wait_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Roku') }}"
          - service: switch.turn_off
            entity_id: switch.echo_through_receiver
        turn_off:
          - service: switch.turn_off
            entity_id: switch.roku
      
      echo_through_receiver:
        value_template: >
          {{ is_state_attr('media_player.yamaha_receiver_zone_2', 'source', 'Echo')
             and is_state_attr('media_player.yamaha_receiver', 'source', 'Echo')
             and is_state('switch.floating_outlet_switch', 'on') }}
        turn_on:
          - service: script.echo_outlet_power
            data:
              power: 'on'
          - service: script.yamaha_power
            data:
              media_player: media_player.yamaha_receiver
              power: 'on'
          - service: script.yamaha_set_volume
            data:
              media_player: media_player.yamaha_receiver
              volume: 0.7
          - service: script.yamaha_select_source
            data:
              media_player: media_player.yamaha_receiver
              source: Echo
          - service: script.yamaha_power
            data:
              media_player: media_player.yamaha_receiver_zone_2
              power: 'on'
          - service: script.yamaha_set_volume
            data:
              media_player: media_player.yamaha_receiver_zone_2
              volume: 0.7
          - service: script.yamaha_select_source
            data:
              media_player: media_player.yamaha_receiver_zone_2
              source: Echo
        turn_off:
          - service: script.turn_off_audio_1
          - service: script.yamaha_power
            data:
              media_player: media_player.yamaha_receiver_zone_2
              power: 'off'
          - service: script.echo_outlet_power
            data:
              power: 'off'
      ### SOURCES FOR RECEIVER ###
      
      # Xbox Source
      xbox_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Xbox One') }}"
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Xbox One
        turn_off:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Xbox One
      # Playstation Source
      playstation_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Playstation 4') }}"
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Playstation 4
        turn_off:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Playstation 4
      # Playstation Source
      nintendo_switch_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Switch') }}"
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Switch
        turn_off:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Switch
      # Roku Source
      roku_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Roku') }}"
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Roku
        turn_off:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Roku
      # Phone Source
      phone_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Phone') }}"
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Phone
        turn_off:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Phone
      # Alexa Source
      alexa_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Echo') }}"
        turn_on:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Echo
        turn_off:
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Echo