# Template Switches

- platform: template
  switches:
            
      # Party mode
      party_mode:
        unique_id: party_mode
        friendly_name: Party Mode
        value_template: >
          {% set switches = expand('switch.echo_through_receiver', 'switch.hyperion_rainbow_swirl_fast', 'switch.lzw45_mood_lighting') | list %}
          {{ switches | selectattr('state', 'eq', 'on') | list | count == switches | count }}
        turn_on:
        - service: script.party_on
        turn_off:
        - service: script.party_off

      # LZW MOOD LIGHTING
      lzw45_mood_lighting:
        unique_id: lzw45_mood_lighting
        friendly_name: Mood Lighting
        value_template: "{{ states('input_text.lzw45_last_effect') != 'off' }}"
        turn_on:
        - service: input_number.set_value
          data:
            entity_id: input_number.quick_strip_color_temp
            value: 2700
        - service: input_select.select_option
          data:
            entity_id: input_select.quick_strip_effect
            option: solid
        turn_off:
        - choose:
          - conditions:
            - condition: template
              value_template: "{{ is_state('input_select.quick_strip_effect', 'off') }}"
            sequence:
            - service: script.lzw45_ui_quick_effect
            - service: input_text.set_value
              data:
                entity_id: input_text.lzw45_last_effect
                value: "off"
          default:
            service: input_select.select_option
            data:
              entity_id: input_select.quick_strip_effect
              option: 'off'

      # INSIDE LIGHTS SWITCH
      inside:
        value_template: "{{ is_state('group.inside_area','on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.inside_area
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.inside_area
      
      # OUTSIDE LIGHTS SWITCH
      outside:
        value_template: "{{ is_state('group.outside_area','on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.outside_area
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.outside_area
      
      # UPSTAIRS LIGHTS SWITCH
      upstairs:
        value_template: "{{ is_state('group.upstairs_area','on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.upstairs_area
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.upstairs_area
      
      # DOWNSTAIRS LIGHTS SWITCH
      downstairs:
        value_template: "{{ is_state('group.downstairs_area','on') }}"
        turn_on:
          service: homeassistant.turn_on
          data:
            entity_id: group.downstairs_area
        turn_off:
          service: homeassistant.turn_off
          data:
            entity_id: group.downstairs_area
      
      # XBOX HARMONY ACTIVITY
      xbox_one:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Xbox One') }}"
        turn_on:
        - service: script.harmony_activity_on
          data:
            activity: Xbox One
        turn_off: &harmony_activity_off
        - service: script.harmony_activity_off
      
      # PLAYSTATION HARMONY ACTIVITY
      playstation:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Playstation') }}"
        turn_on:
        - service: script.harmony_activity_on
          data:
            activity: Playstation
        turn_off: *harmony_activity_off
      
      # SWITCH HARMONY ACTIVITY
      switch:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Switch') }}"
        turn_on:
        - service: script.harmony_activity_on
          data:
            activity: Switch
        turn_off: *harmony_activity_off
      
      # TV HARMONY ACTIVITY
      tv:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'TV') }}"
        turn_on:
        - service: script.harmony_activity_on
          data:
            activity: TV
        turn_off: *harmony_activity_off
      
      # CHROMECAST HARMONY ACTIVITY
      chromecast:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Chromecast') }}"
        turn_on:
        - service: script.harmony_activity_on
          data:
            activity: Chromecast
        turn_off: &chromecast_off
        - service: script.harmony_activity_off
        - service: script.stop_casting

      # OFF ACTIVITY
      poweroff:
        value_template: "{{ not is_state_attr('remote.living_room', 'current_activity', 'PowerOff') }}"
        turn_on: &harmony_all_off
          - service: script.harmony_all_off
        turn_off: *harmony_all_off
        
      # ROKU HARMONY ACTIVITY
      roku:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Roku') }}"
        turn_on:
        - service: script.harmony_activity_on
          data:
            activity: Roku
        turn_off: *harmony_activity_off
            
      # NETFLIX
      netflix:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Netflix') }}
        turn_on:
        - service: script.roku_source_on
          data:
            source: Netflix
        turn_off: &turn_off_roku
        - service: switch.turn_off
          entity_id: switch.roku
            
      # HBO
      hbo:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'HBO Max') }}
        turn_on:
        - service: script.roku_source_on
          data:
            source: HBO Max
        turn_off: *turn_off_roku
            
      # Hulu
      hulu:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Hulu') }}
        turn_on:
        - service: script.roku_source_on
          data:
            source: Hulu
        turn_off: *turn_off_roku
            
      # Prime Video
      prime_video:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Prime Video') }}
        turn_on:
        - service: script.roku_source_on
          data:
            source: Prime Video
        turn_off: *turn_off_roku

            
      # Disney Plus
      disney_plus:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Disney Plus') }}
        turn_on:
        - service: script.roku_source_on
          data:
            source: Disney Plus
        turn_off: *turn_off_roku
            
      # Plex
      plex:
        value_template: >
          {{ is_state('switch.roku', 'on') and 'plex' in state_attr('media_player.roku_living_room', 'source') | string | lower }}
        turn_on:
        - service: script.roku_source_on
          data:
            source: >
              {%- set player = expand('media_player.roku_living_room') | first %}
              {%- set ns = namespace(ret=[]) %}
              {%- for source in player.attributes.source_list %}
                {%- if 'plex' in source.lower() %}
                  {%- set ns.ret = ns.ret + [ source ] %}
                {%- endif %}
              {%- endfor %}
              {{ ns.ret | first | default('Plex - Free Movies & TV') }}
        turn_off: *turn_off_roku

      # Peacock
      peacock:
        value_template: >
          {{ is_state('switch.roku', 'on') and 
             is_state_attr('media_player.roku_living_room', 'source', 'Peacock TV') }}
        turn_on:
        - service: script.roku_source_on
          data:
            source: Peacock TV
        turn_off: *turn_off_roku

      echo_through_receiver:
        value_template: >
          {{ is_state_attr('media_player.yamaha_receiver_zone_2', 'source', 'Echo')
             and is_state_attr('media_player.yamaha_receiver', 'source', 'Echo')
             and is_state('switch.floating_outlet_switch', 'on') }}
        turn_on:
        - service: script.echo_through_receiver_on
        turn_off:
        - service: script.echo_through_receiver_off

      ### SOURCES FOR RECEIVER ###
      
      # Xbox Source
      xbox_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Xbox One') }}"
        turn_on: &xbox_source
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Xbox One
        turn_off: *xbox_source

      # Playstation Source
      playstation_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Playstation 4') }}"
        turn_on: &playstation_source
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Playstation 4
        turn_off: *playstation_source

      # Switch Source
      nintendo_switch_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Switch') }}"
        turn_on: &nintendo_switch_source
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Switch
        turn_off: *nintendo_switch_source

      # Roku Source
      roku_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Roku') }}"
        turn_on: &roku_source
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Roku
        turn_off: *roku_source

      # Phone Source
      phone_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Phone') }}"
        turn_on: &phone_source
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Phone
        turn_off: *phone_source

      # Phone Source
      chromecast_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Chromecast') }}"
        turn_on: &chromecast_source
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Chromecast
        turn_off: *chromecast_source

      # Alexa Source
      alexa_source:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver', 'source', 'Echo') }}"
        turn_on: &alexa_source
          - service: media_player.select_source
            data:
              entity_id: media_player.yamaha_receiver
              source: Echo
        turn_off: *alexa_source

      # Surround Sound Modes

      # Sports Surround Mode
      surround_mode_sports:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','Sports') }}"
        turn_on:
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: Sports
        turn_off: &surround_standard
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: Standard

      # Action Game Surround Mode
      surround_mode_action_game:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','Action Game') }}"
        turn_on:
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: Action Game
        turn_off: *surround_standard

      # Roleplaying Game Surround Mode
      surround_mode_roleplaying_game:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','Roleplaying Game') }}"
        turn_on:
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: Roleplaying Game
        turn_off: *surround_standard

      # Standard Surround Mode
      surround_mode_standard:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','Standard') }}"
        turn_on: *surround_standard
        turn_off: *surround_standard

      # Sci-Fi Surround Mode
      surround_mode_sci_fi:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','Sci-Fi') }}"
        turn_on:
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: Sci-Fi
        turn_off: *surround_standard

      # Adventure Surround Mode
      surround_mode_adventure:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','Adventure') }}"
        turn_on:
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: Adventure
        turn_off: *surround_standard

      # Drama Surround Mode
      surround_mode_drama:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','Drama') }}"
        turn_on:
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: Drama
        turn_off: *surround_standard

      # Surround Decoder Surround Mode
      surround_mode_surround_decoder:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','Surround Decoder') }}"
        turn_on:
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: Surround Decoder
        turn_off: *surround_standard

      # 7ch Stereo Surround Mode
      surround_mode_7ch_stereo:
        value_template: "{{ is_state_attr('media_player.yamaha_receiver','sound_mode','7ch Stereo') }}"
        turn_on:
        - service: media_player.select_sound_mode
          data: 
            entity_id: media_player.yamaha_receiver
            sound_mode: 7ch Stereo
        turn_off: *surround_standard

      hyperion:
        unique_id: hyperion
        value_template: "{{ is_state('light.gpio_18_tv', 'on') }}"
        turn_on:
        - service: light.turn_on
          target:
            entity_id: light.gpio_18_tv
          data:
            brightness: 255
        turn_off:
        - service: light.turn_off
          target:
            entity_id: light.gpio_18_tv

      hyperion_usb_capture:
        unique_id: hyperion_usb_capture
        value_template: >
          {%- set entity = 'light.gpio_18_tv' %}
          {{ is_state(entity, 'on') and is_state_attr(entity, 'effect', 'USB Capture') }}
        turn_on:
        - service: light.turn_on
          target:
            entity_id: light.gpio_18_tv
          data:
            brightness: 255
            effect: USB Capture
        turn_off:
        - service: light.turn_off
          target:
            entity_id: light.gpio_18_tv

      hyperion_cinema:
        unique_id: hyperion_cinema
        value_template: >
          {%- set entity = 'light.gpio_18_tv' %}
          {{ is_state(entity, 'on') and is_state_attr(entity, 'effect', 'Cinema dim lights') }}
        turn_on:
        - service: light.turn_on
          target:
            entity_id: light.gpio_18_tv
          data:
            brightness: 255
            effect: Cinema dim lights
        turn_off:
        - service: light.turn_off
          target:
            entity_id: light.gpio_18_tv

      hyperion_rainbow_swirl_fast:
        unique_id: hyperion_rainbow_swirl_fast
        value_template: >
          {%- set entity = 'light.gpio_18_tv' %}
          {{ is_state(entity, 'on') and is_state_attr(entity, 'effect', 'Rainbow swirl fast') }}
        turn_on:
        - service: light.turn_on
          target:
            entity_id: light.gpio_18_tv
          data:
            brightness: 255
            effect: Rainbow swirl fast
        turn_off:
        - service: light.turn_off
          target:
            entity_id: light.gpio_18_tv

      cast_workout_core:
        unique_id: cast_workout_core
        value_template: >
          {{ states('media_player.chromecast') in ['playing','paused'] and 
            is_state_attr('media_player.chromecast', 'media_title', 'Core') }}
        turn_on: &cast_workout_core
        - service: script.cast_workout_video
          data:
            workout: Core
        turn_off: *chromecast_off
        
      cast_workout_cardio_kickboxing:
        unique_id: cast_workout_cardio_kickboxing
        value_template: >
          {{ states('media_player.chromecast') in ['playing','paused'] and 
            is_state_attr('media_player.chromecast', 'media_title', 'Cardio Kickboxing') }}
        turn_on: &cast_workout_cardio_kickboxing
        - service: script.cast_workout_video
          data:
            workout: Cardio Kickboxing
        turn_off: *chromecast_off

      cast_workout_lower_body:
        unique_id: cast_workout_lower_body
        value_template: >
          {{ states('media_player.chromecast') in ['playing','paused'] and 
            is_state_attr('media_player.chromecast', 'media_title', 'Lower Body') }}
        turn_on: &cast_workout_lower_body
        - service: script.cast_workout_video
          data:
            workout: Lower Body
        turn_off: *chromecast_off

      cast_workout_total_body:
        unique_id: cast_workout_total_body
        value_template: >
          {{ states('media_player.chromecast') in ['playing','paused'] and 
            is_state_attr('media_player.chromecast', 'media_title', 'Total Body') }}
        turn_on: &cast_workout_total_body
        - service: script.cast_workout_video
          data:
            workout: Total Body
        turn_off: *chromecast_off

      cast_workout_upper_body:
        unique_id: cast_workout_upper_body
        value_template: >
          {{ states('media_player.chromecast') in ['playing','paused'] and 
            is_state_attr('media_player.chromecast', 'media_title', 'Upper Body') }}
        turn_on: &cast_workout_upper_body
        - service: script.cast_workout_video
          data:
            workout: Upper Body
        turn_off: *chromecast_off