title: Home
# Exclude entities from "Unused entities" view

preload_cards:
- horizontal-stack
- vertical-stack
- entities

preload_rows:
- sensor-entity

custom_header: !include lovelace/custom_header.yaml

background: center / cover no-repeat url("/local/images/background.jpg") fixed
# views:
# - title: main
#   cards:
#   - type: entities
#     entities:
#     - person.petro
#     - person.lambo

popup_cards: !include lovelace/views/popups.yaml

views: !include lovelace/views/master.yaml