title: Home
# Exclude entities from "Unused entities" view
resources: !include lovelace/resources.yaml
custom_header: !include lovelace/custom_header.yaml

background: center / cover no-repeat url("/local/images/background.jpg") fixed
views: !include lovelace/views/master.yaml