title: Home
# Exclude entities from "Unused entities" view

preload_cards:
- horizontal-stack
- vertical-stack
- entities
- markdown

preload_rows:
- sensor-entity

views: !include lovelace/views/master.yaml