- alias: Turn off Outside Cameras based on temperature
  id: turn_off_outside_cameras_based_on_temperature
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_shutoff
    from: 'off'
    to: 'on'
  action:
  - service: script.notify
    data:
      message: >
        [{{ now().strftime('%-I:%M:%S %p') }}] Temperature is moving below 16°F, turning off the driveway and backyard camera.
  - service: switch.turn_off
    data:
      entity_id:
      - switch.driveway_camera_port
      - switch.patio_camera_port

- alias: Turn on Outside Cameras based on temperature
  id: turn_on_outside_cameras_based_on_temperature
  trigger:
  - platform: state
    entity_id: binary_sensor.camera_turn_on
    from: 'off'
    to: 'on'
  action:
  - service: script.notify
    data:
      message: >
        [{{ now().strftime('%-I:%M:%S %p') }}] Temperature is moving above 20°F, turning on the driveway and backyard camera.
  - service: switch.turn_on
    data:
      entity_id:
      - switch.driveway_camera_port
      - switch.patio_camera_port