
# notify.mobile_app_petro

- alias: Frigate Notifications - Backyard
  id: frigate_notifications_backyard
  trigger: 
  - payload: backyard
    <<: &trigger
      platform: mqtt
      topic: frigate/events
      value_template: >
        {{ value_json.after.camera }}
  <<: &automation
    mode: single
    max_exceeded: silent
    variables:
      id: '{{ trigger.payload_json.after.id }}'
      camera: '{{ trigger.payload_json.after.camera }}'
      camera_name: '{{ camera | replace("_", " ") }}'
      label: '{{ trigger.payload_json.after.label }}'
      entered_zones: "{{ trigger.payload_json.after.entered_zones }}"
      zones: 
      - the_driveway
      - patio
      - deck
      - porch
      zone_names:
        the_driveway_shadow: the driveway
        the_driveway: the driveway
        front_left_yard: the front yard
        front_right_yard: the front yard
        street: the street
        patio: the patio
        back_right_yard: the back yard
        deck: the deck
        lawn: the back yard
        neighboors: the neighboors yard
        porch: the porch
        walkway: the front yard
      in_zone: >
        {{ zones | select('in', entered_zones) | list | length > 0 }}
      the_unknown: the unknown
      zone_phrase: >
        {%- set ns = namespace(zones=[]) %}
        {%- for z in entered_zones %}
          {% set ns.zones = ns.zones + [ zone_names.get(z) or the_unknown ] %}
        {%- endfor %}
        {%- set names = ns.zones | unique | list %}
        {%- if names | length <= 1 %}
          {{ names | first | default(the_unknown) }}
        {%- else %}
          {{ names[:-1] | join(', ') }}, and {{ names[-1] }}
        {%- endif %}
      is_armed: >
        {{ states('input_select.home_security') in ['armed'] }}
      is_valid: >
        {{ trigger.payload_json.type != "end" and in_zone and is_armed }}
      message: >
        A {{ label }} was detected on {{ zone_phrase }}.
  
    condition:
    - condition: template
      value_template: "{{ is_valid }}"
  
    action:
    - parallel:
      - sequence:
        - service: script.silencable_frigate_notification
          data:
            id: '{{ id }}'
            camera: '{{ camera }}'
            message: "{{ message }}"
            notify: notify.mobile_app_petro
            persistent_notification: on
  
      - sequence:
        - service: script.silencable_frigate_notification
          data:
            id: '{{ id }}'
            camera: '{{ camera }}'
            message: "{{ message }}"
            notify: notify.mobile_app_lindsays_iphone
            persistent_notification: off

- alias: Frigate Notifications - Driveway
  id: frigate_notifications_driveway
  trigger: 
  - payload: driveway
    <<: *trigger
  <<: *automation
      
- alias: Frigate Notifications - Deck 1
  id: frigate_notifications_deck_1
  trigger: 
  - payload: deck1
    <<: *trigger
  <<: *automation
      
- alias: Frigate Notifications - Deck 2
  id: frigate_notifications_deck_2
  trigger: 
  - payload: deck2
    <<: *trigger
  <<: *automation
      
- alias: Frigate Notifications - Porch
  id: frigate_notifications_porch
  trigger: 
  - payload: porch
    <<: *trigger
  <<: *automation
