
# notify.mobile_app_petro

- alias: Frigate Notifications - Petro - Backyard & Driveway
  id: frigate_notifications_petro_backyard_and_driveway
  mode: single
  trigger: &triggers
  - platform: mqtt
    topic: frigate/events
    payload: driveway
    value_template: >
      {{ value_json.after.camera }}
  - platform: mqtt
    topic: frigate/events
    payload: backyard
    value_template: >
      {{ value_json.after.camera }}
  variables: &variables
    id: '{{ trigger.payload_json.after.id }}'
    camera: '{{ trigger.payload_json.after.camera }}'
    camera_name: '{{ camera | replace("_", " ") }}'
    label: '{{ trigger.payload_json.after.label }}'
    entered_zones: "{{ trigger.payload_json.after.entered_zones }}"
    zones: 
    - the_driveway
    - patio
    zone_names:
      the_driveway: the driveway
      front_left_yard: the front yard
      front_right_yard: the front yard
      street: the street
      patio: the patio
      back_right_yard: the back yard
    in_zone: >
      {{ zones | select('in', entered_zones) | list | length > 0 }}
    the_unknown: the unknown
    zone_phrase: >
      {%- set ns = namespace(zones=[]) %}
      {%- for z in entered_zones %}
        {% set ns.zones = ns.zones + [ zone_names.get(z) or the_unknown ] %}
      {%- endfor %}
      {%- set names = ns.zones | unique | list %}
      {%- if names | length <= 1 %}
        {{ names | first | default(the_unknown) }}
      {%- else %}
        {{ names[:-1] | join(', ') }}, and {{ names[-1] }}
      {%- endif %}
    is_valid: >
      {{ trigger.payload_json.type != "end" and in_zone }}
    message: >
      A {{ label }} was detected in {{ zone_phrase }}.
  condition: &condition
  - condition: template
    value_template: "{{ is_valid }}"
  action:

  - service: script.frigate_notification_petro
    data: &data
      id: '{{ id }}'
      camera: '{{ camera }}'
      message: "{{ message }}"
      silence: "{{ silence }}"

# notify.mobile_app_lindsays_iphone

- alias: Frigate Notifications - Lambo - Backyard & Driveway
  id: frigate_notifications_lambo_backyard_and_driveway
  mode: single
  trigger: *triggers
  variables: *variables
  condition: *condition
  action:
  - service: script.frigate_notification_lambo
    data: *data