- alias: Timed Event - Holiday Lights
  id: indoor_holiday_lights
  mode: parallel
  trigger:
    - id: indoor
      platform: state
      entity_id: binary_sensor.indoor_holiday
      not_from:
        - unknown
        - unavailable
    - id: outdoor_on
      platform: sun
      event: sunset
    - id: outdoor_off
      platform: sun
      event: sunrise
  variables:
    continue: >
      {% if trigger.platform == 'state' %}
        {{ trigger | default(none) is not none and trigger.to_state is defined and trigger.from_state is defined }}
      {% else %}
        True
      {% endif %}
    to_state: >
      {% if trigger.platform == 'state' %}
        {{ trigger.to_state.state | default if continue else None }}
      {% else %}
        {{ trigger.id.split('_')[-1] }}
      {% endif %}
    indoor:
      - switch.indoor_holiday
    outdoor: []
    target: >
      {{ indoor if trigger.id == 'indoor' else outdoor }}
  condition:
    - condition: template
      value_template: "{{ target | count > 0 and continue and to_state in ['on','off'] }}"
  action:
    - service: switch.turn_{{ to_state }}
      target:
        entity_id: "{{ target }}"
