- alias: MQTT Discovery
  id: aafa91b8-a2e2-4df2-9412-536288327566
  mode: single
  trigger:
    - platform: homeassistant
      event: start
  action:

  # MQTT Discovery
  - service: script.turn_on
    target:
      entity_id: script.irrigation_mqtt_discovery

- alias: Set Next Irrigation
  id: 54f20352-b2ba-44d7-80f5-44ada2469dbc
  mode: restart
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: "00:00:00"
    - platform: state
      entity_id:
      - input_datetime.irrigation_program_start
      - switch.back_yard_status
      - switch.front_yard_status
      - number.back_yard_day_cycle
      - number.front_yard_day_cycle
      - switch.rain_bird_sprinkler_1_status
      - switch.rain_bird_sprinkler_2_status
      - switch.rain_bird_sprinkler_3_status
      - switch.rain_bird_sprinkler_5_status
      - switch.rain_bird_sprinkler_6_status
      - switch.rain_bird_sprinkler_7_status
      - switch.rain_bird_sprinkler_8_status
      - number.rain_bird_sprinkler_1_program_duration
      - number.rain_bird_sprinkler_2_program_duration
      - number.rain_bird_sprinkler_3_program_duration
      - number.rain_bird_sprinkler_5_program_duration
      - number.rain_bird_sprinkler_6_program_duration
      - number.rain_bird_sprinkler_7_program_duration
      - number.rain_bird_sprinkler_8_program_duration
      - sensor.rain_bird_sprinkler_1_last_run
      - sensor.rain_bird_sprinkler_2_last_run
      - sensor.rain_bird_sprinkler_3_last_run
      - sensor.rain_bird_sprinkler_5_last_run
      - sensor.rain_bird_sprinkler_6_last_run
      - sensor.rain_bird_sprinkler_7_last_run
      - sensor.rain_bird_sprinkler_8_last_run
  action: 
  - service: script.get_next_irrigations
    response_variable: irrigations
  - condition: template
    value_template: "{{ irrigations.zones | count > 0 }}"
  - repeat:
      for_each: "{{ irrigations.zones }}"
      sequence:
      - service: script.mqtt_automated_states
        data:
          domain: sensor
          unique_id: "{{ repeat.item.zone_next_run_id }}"
          state: "{{ repeat.item.zone_next_run }}"

- alias: Start Irrigation Cycle
  id: 1c67152d-d153-41a9-b5a7-78ce036fecbf
  mode: single
  trigger:
  - platform: time
    at: &entities
    - sensor.rain_bird_sprinkler_1_start
    - sensor.rain_bird_sprinkler_2_start
    - sensor.rain_bird_sprinkler_3_start
    - sensor.rain_bird_sprinkler_5_start
    - sensor.rain_bird_sprinkler_6_start
    - sensor.rain_bird_sprinkler_7_start
    - sensor.rain_bird_sprinkler_8_start
  variables:
    entities: *entities

    # Ensure we have an isoformatted utc timestamp that matches the most recent minute.
    trigger_time: >
      {{ trigger.now.astimezone(utcnow().tzinfo).replace(second=0, microsecond=0).isoformat() }}

    start: >
      {{ entities | select('is_state', trigger_time) | first | default }}

    object_id: >
      {{ start | regex_findall('sensor.(.*)_start') | first }}

    switch: switch.{{ object_id }}
    number: number.{{ object_id }}_program_duration
    last_run_unique_id: >
      {% set identifier = device_attr('sensor.{0}_last_run'.format(object_id), 'identifiers') | list | first | last %}
      {{ identifier | slugify | replace('_', '') ~ 'lr' }}
    last_run_attributes: >
      {{ dict(by='irrigation' if is_state('binary_sensor.rain_bird_controller_rainsensor', 'off') else 'rain') }}

    # Default to zero for if checks when failing
    duration: >
      {{ states(number) | int(0) }}

  condition:
  - condition: template
    value_template: "{{ duration > 0 }}"
  action:
  - service: script.mqtt_automated_states
    data:
      domain: sensor
      unique_id: "{{ last_run_unique_id }}"
      state: "{{ trigger_time }}"
      attributes: "{{ last_run_attributes }}"
  - if: "{{ is_state('binary_sensor.rain_bird_controller_rainsensor', 'off') }}"
    then:
    - service: rainbird.start_irrigation
      data:
        entity_id: "{{ switch }}"
        duration: "{{ duration }}"

- alias: Check Rain Today
  id: a9040111-cd2f-4dd4-9a6b-518bfa2e90e9
  mode: restart
  triggers:
    - trigger: time
      at: input_datetime.irrigation_program_start
  variables:
    trigger_time: >
      {{ trigger.now.astimezone(utcnow().tzinfo).replace(second=0, microsecond=0).isoformat() }}
  conditions:
  - condition: state
    entity_id: binary_sensor.rain_bird_controller_rainsensor
    state: 'on'
  - condition: state
    entity_id: binary_sensor.irrigation_season
    state: 'on'
  actions:
  - action: script.set_last_irrigation
    data:
      time: "{{ (trigger_time | as_datetime).time() }}"
      date: "{{ (trigger_time | as_datetime).date() }}"
      switches: "{{ integration_entities('rainbird') | select('match', '^switch.') | list }}"
      reason: rain


- alias: Valve Reminders
  id: 33596fc1-7dbf-4837-a589-953f2d5d072a
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '15:30:00'
    - platform: time
      at: '19:00:00'
  variables:
    target_dates: >
      {% set ns = namespace(dates=[]) %}
      {%- for offset in [7, 1] %}
      {%- set ns.dates = ns.dates + [(today_at() + timedelta(days=offset)).date() | string] %}
      {%- endfor %}
      {{ ns.dates }}
    entities:
    - sensor.irrigation_season_start
    - sensor.irrigation_season_end
    events: >
      {%- from 'easy_time.jinja' import speak_the_days %}
      {%- set phrase = 'Turn o{} the water irrigation shutoff value{}{}' %}
      {%- set ns = namespace(items=[]) %}
      {%- for e in entities %}
        {%- set dt = states(e) | as_datetime %}
        {%- set date = dt.date() | string %}
        {%- set name = state_attr(e, 'friendly_name') %}
        {%- set p = 'n' if 'Start' in name else 'ff' %}
        {%- set f = speak_the_days(dt) %}
        {%- set m = ' ' if 'in' in f else ' before ' %}
        {%- set ns.items = ns.items + [
          dict(
            title=name,
            when=date,
            message=phrase.format(p, m, f)
          )
        ] -%}
      {%- endfor %}
      {{ ns.items }}
    event: >
      {{ events | selectattr('when', 'in', target_dates) | list | first | default(None) }}
  condition:
  - condition: template
    value_template: "{{ event is not none }}"
  action:
  - service: script.notify
    data:
      title: "{{ event.title }}"
      message: "{{ event.message }}"
