- alias: MQTT - Store Door States
  id: mqtt_store_door_states
  mode: parallel
  trigger:
  - platform: state
    entity_id:
    - input_boolean.test_door_helper
    to: 'on'
  variables:
    who: >
      {{ state_attr('sensor.people_at_home', 'or') }}
  action:
  - service: script.mqtt_automated_states
    data:
      domain: sensor
      unique_id: >
        {%- set domain, object_id = trigger.to_state.entity_id.split('.') %}
        {{ object_id.split('_')[:-1] | join('_') ~ '_last_opened' }}
      state: >
        {% set datetime = datetime | default(now()) %}
        {{ as_timestamp(datetime) | timestamp_custom("%Y-%m-%dT%H:%M:%S.%f+00:00", datetime.tzinfo == 'UTC') }}
      attributes: "{{ { 'who': who } | tojson }}"

- alias: MQTT - Store Door States Discovery
  id: mqtt_store_door_states_discovery
  mode: single
  trigger:
  - platform: homeassistant
    event: start
  variables:
    doors:
    - test_door_last_opened
  action:
  - repeat:
      count: "{{ doors | length }}"
      sequence:
      - service: script.mqtt_automated_config
        data:
          domain: sensor
          unique_id: "{{ doors[repeat.index - 1] }}"
          device_class: timestamp