- alias: Reaction - Keep Sunset Switches On.
  id: reaction_keep_sunset_switches_on
  mode: parallel
  trigger:
  - platform: state
    entity_id:
    - switch.passenger_sconce
    - switch.sconces_garage
    - switch.sconces_main_entrance
    to: 'off'
  variables:
    continue: >
      {{ trigger | default(none) is not none and trigger.to_state is defined and trigger.from_state is defined }}
  condition:
  - condition: template
    value_template: "{{ continue }}"
  action:
  - service: switch.turn_on
    target:
      entity_id: "{{ trigger.entity_id }}"
  - service: script.notify
    data:
      title: "Sunset Switch Turned Off"
      message: >
        {{ state_attr(trigger.entity_id, 'friendly_name') }} door sconce switch was turned off, turning back on.
  - service: notify.alexa_media
    data:
      message: Jim counter action initiative in affect. Turning on {{ state_attr(trigger.entity_id, 'friendly_name') }} door sconces.
      data:
        type: announce
      target: media_player.living_room_dot
  - condition: sun
    after: sunrise
    before: sunset
  - delay:
      seconds: 5
  - service: light.turn_off
    target:
      entity_id: light.outside_sunset
