- alias: Ignore Spook Repair
  id: repair_ignore_spook_repair
  trigger:
  - platform: state
    entity_id: event.repair
  variables:
    continue: >
      {{ trigger | default(none) is not none and trigger.to_state is defined and trigger.from_state is defined }}
    attrs: >
      {{ trigger.to_state.attributes | default({}) if continue else {} }}
    issue_id: >
      {{ attrs.get('issue_id') }}
    target: >
      {{ issue_id if 'timed_event_snapshot_status' in issue_id else None }}
  condition:
  - condition: template
    value_template: "{{ target is not none }}"
  action:
  - service: repairs.remove
    data:
      issue_id: "{{ target }}"
