- alias: Daily Snapshot
  id: daily_snapshot
  trigger:
    - platform: time
      at: '04:00:00'
  action:
    - service: hassio.addon_start
      data:
        addon: 954f2f4e_remote_backup
    - service: persistent_notification.create
      data:
        title: Daily Snapshot
        message: "Successfully created daily snapshot."
        notification_id: Daily Snapshot
    
- alias: Garbage Day Message
  id: garbage_day_message
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '15:30:00'
    - platform: time
      at: '19:00:00'
  condition:
    - condition: time
      weekday:
        - mon
  action:
    - service: notify.homeowners
      data:
        message: "Trash day tomorrow!"
        
- alias: Change Filters Message
  id: change_filters_message
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '19:00:00'
  condition:
    - condition: template
      value_template: "{{ now().day == 1 and now().month in [ 1, 4, 7, 10 ] }}"
  action:
    - service: notify.homeowners
      data:
        message: "Change HVAC filter."
            
- alias: Mosby Heartworm and Flee Medication.
  id: mosby_heartworm
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '19:00:00'
  condition:
    - condition: template
      value_template: "{{ now().day == 1 }}"
  action:
    - service: notify.homeowners
      data:
        message: "Give mosby heartworm and flee medication."

- alias: DST Warning
  id: dst_warning
  trigger:
    - platform: time
      at: '10:00:00'
    - platform: time
      at: '19:00:00'
  condition:
    - condition: template
      value_template: >
        {{ state_attr('sensor.dst', 'next').days_to_event in [7,1] }}
  action:
    - service: notify.homeowners
      data:
        message: >
          {%- set next = state_attr('sensor.dst', 'next') %}
          {%- set plural = 's' if next.days_to_event > 1 else '' %}
          "Daylight savings in {{ next.days_to_event }} day{{plural}}, you will {{ next.phrase }}!"

- alias: Indoor Christmas Lights
  id: indoor_christmas_lights
  trigger:
  - platform: time
    at: '16:00:00'
  - platform: time
    at: '23:00:00'
  variables:
    time: >
      {%- set dt = trigger.now | default(now()) %}
      {{ dt.time().replace(second=0, microsecond=0) | string }}
  condition:
  - condition: template
    value_template: "{{ is_state('sensor.christmas_season', 'on') }}"
  action:
  - service: switch.turn_o{{ 'n' if time == '16:00:00' else 'ff' }}
  