substitutions:
  name: apollo-air-1-1ecac0
  friendly_name: Apollo AIR-1 1ecac0
packages:
  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: cie3oLORtRNT3Wb9w0a5Mz7SsipiZksFH+hL+tyN4mM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - id: !extend sen55
    humidity:
      name: Humidity
      id: humidity
      filters:
        - lambda: return 1.048 * x + 6.7969;
    temperature:
      name: Temperature
      id: temperature
      filters:
        - lambda: return 0.7733 * x + 5.9699;
