esphome:
  name: basement-esp32
  friendly_name: Basement Esp32

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret game_room_ota_password

wifi:
  ssid: !secret wifi_iot_server_ssid
  password: !secret wifi_iot_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Basement-Esp32 Fallback Hotspot"
    password: !secret wifi_iot_password

captive_portal:

esp32_ble_tracker:

bluetooth_proxy:

i2c:
- sda: 21
  scl: 22
  scan: true

switch:
  - platform: restart
    name: "Restart"

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 30s

  - platform: uptime
    name: Ethernet Uptime

  - platform: template
    name: Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    unit_of_measurement: 'B'
    state_class: measurement

  - platform: xiaomi_cgdk2
    mac_address: !secret xiaomi_cgdk2_4_mac
    bindkey: !secret xiaomi_cgdk2_4_bindkey
    temperature:
      name: Basement CGDK2 Temperature
    humidity:
      name: Basement CGDK2 Humidity
    battery_level:
      name: Basement CGDK2 Battery Level