esphome:
  name: master_closet_esp32
  platform: ESP32
  board: mhetesp32devkit

wifi:
  ssid: !secret wifi_iot_server_ssid
  password: !secret wifi_iot_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dining Room Esp32"
    password: !secret wifi_fallback_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

switch:
  - platform: restart
    name: "Master Bedroom ESP32 Restart"

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: !secret mijia_ble_temperature_3
    temperature:
      name: "Master Bathroom Temperature"
      device_class: "temperature"
      state_class: "measurement"
    humidity:
      name: "Master Bathroom Humidity"
      device_class: "humidity"
      state_class: "measurement"
    battery_level:
      name: "Master Bathroom Temperature Sensor Battery Level"
      
  - platform: template
    name: Master Bathroom Temperature Sensor Number
    lambda: |-
      return 3;
    update_interval: 86400s
      
  - platform: xiaomi_lywsdcgq
    mac_address: !secret mijia_ble_temperature_5
    temperature:
      name: "Master Bedroom Temperature"
      device_class: "temperature"
      state_class: "measurement"
    humidity:
      name: "Master Bedroom Humidity"
      device_class: "humidity"
      state_class: "measurement"
    battery_level:
      name: "Master Bedroom Temperature Sensor Battery Level"

  - platform: template
    name: Master Bedroom Temperature Sensor Number
    lambda: |-
      return 5;
    update_interval: 86400s

  - platform: uptime
    name: Master Bedroom ESP32 Ethernet Uptime

  - platform: template
    name: Master Bedroom ESP32 Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    unit_of_measurement: 'B'
    state_class: measurement

  - platform: xiaomi_miscale
    mac_address: !secret xiaomi_miscale_mac
    weight:
      name: Master Scale Weight
      unit_of_measurement: lb
      state_class: measurement
      device_class: weight
      icon: mdi:weight-lb
      accuracy_decimals: 2
      filters:
      - multiply: 2.20462
    impedance:
      name: Master Scale Impedance
      unit_of_measurement: 'Î©'
      state_class: measurement
      icon: mdi:omega
      accuracy_decimals: 0
