template:
- triggers:
  - trigger: state
    entity_id: &entities
    - binary_sensor.water_heater_water_leak_detected
    - binary_sensor.right_sink_water_leak_detected
    - binary_sensor.left_sink_water_leak_detected
    - binary_sensor.kitchen_sink_water_leak_detected
    - binary_sensor.powder_room_sink_water_leak_detected
    to:
    - 'on'
    - 'off'
    not_from:
    - unavailable
    - unknown
  variables:
    entities: *entities
    next_state: >
      {{ entities | select('is_state', 'on') | list | count > 0 }}
    area: >
      {{ trigger.entity_id | area_name | lower }}
    what: >
      {{ trigger.to_state.name | lower | replace(area + ' ', '') }}
  binary_sensor:
  - unique_id: c25ba0eb-0ab1-4005-b35e-15bc91e58479
    name: Leak
    device_class: moisture
    state: "{{ next_state }}"
    attributes:
      entity_id: "{{ entities }}"
      message: >
        {%- if next_state %}
          Liquid detected below the {{ area }} {{ what }}
        {%- else %}
          No leak detected
        {%- endif %}

automation:
- alias: Leak Warning
  id: 0705a3d3-e7e4-475f-9063-70e7c6107c83
  description: Notify if there's a leak
  triggers:
  - trigger: state
    entity_id: 
    - binary_sensor.leak
    to: 'on'
  actions:
  - action: script.notify
    data:
      title: Leak Detected!
      message: "{{ state_attr('binary_sensor.leak', 'message') }}"
  - <<: &set_datetime
      action: input_datetime.set_datetime
      target:
        entity_id: input_datetime.leak_annoy
      data:
        datetime: >
          {{ now() + timedelta(minutes=15) }}

- alias: Leak Persistence
  id: 391d15c8-d9de-4937-94e9-c6367690ea4a
  description: Keep notifying if there's a leak.
  triggers:
  - trigger: time
    at: input_datetime.leak_annoy
  conditions:
  - condition: state
    entity_id: binary_sensor.leak
    state: 'on'
  actions:
  - action: script.notify
    data:
      title: Leak Detected!
      message: "{{ message }}"
  - <<: *set_datetime
